mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from . import views

urlpatterns = [
    url(r'^$', views.thepost, name='index'),
    url(r'^thepost', views.thepost, name='thepost'),
]

mysite/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.views.generic import TemplateView
from django import forms
import logging
logger = logging.getLogger(__name__)

# Create your views here.


class NameForm(forms.Form):
    firstname = forms.CharField(label='Your name', max_length=100)
    lastname = forms.CharField(label='Your lastname', max_length=100)


def thepost(request):
    print "thepost request", request
    # if this is a POST request we need to process the form data
    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        form = NameForm(request.POST)
        # check whether it's valid:
        if form.is_valid():
            firstname = form.cleaned_data['firstname']
            lastname = form.cleaned_data['lastname']
            print "thepost form is valid--->", firstname, ":", lastname
            print "current form is ", form            
            # redirect to a new URL:
            return render(request, 'result.html', {'firstname': firstname, 'lastname': lastname})
    # if a GET (or any other method) we'll create a blank form
    else:
        form = NameForm()
    return render(request, 'home.html', {'form': form})

templates/base.html
{% load static %}
<!doctype html>
<html class="no-js" lang="">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <style>
        body {
            padding-top: 50px;
            padding-bottom: 20px;
        }
    </style>
</head>
<body>
</nav>
{% block content %}{% endblock %}

</body>
</html>

templates/home.html
{% extends 'base.html' %} 
{% block content %}

<form action="thepost" method="post">
    {% csrf_token %}
    <label for="id_firstname">Your name:</label>
    <input id="id_firstname" maxlength="100" name="firstname" type="text" required>
    <label for="id_lastname">Your lastname:</label>
    <input id="id_lastname" maxlength="100" name="lastname" type="text" required>
    <input type="submit" value="Submit" />
</form>

{% endblock %}

templates/result.html
{% extends 'base.html' %} 
{% block content %}

<p>Firstname:</p>
<h3>
{{ firstname }}
</h3>
<br>
<p>lastname:</p>
<h4>
{{ lastname }}
</h4>

{% endblock %}